script: true
env:
  global:
  - COMMIT_AUTHOR_NAME: "'Maite Clausell'"
  - COMMIT_AUTHOR_EMAIL: mcm.tradu@gmail.com
  - LOCALES_PATH: src/_locales
deploy:
  provider: script
  script: bash ./deploy/chrome-extension-localization/deploy/deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_6d22f1c3b7da_key -iv $encrypted_6d22f1c3b7da_iv
  -in deploy_key.enc -out deploy_key -d
- git submodule update --init --recursive
